# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 465d0a992733df9182cd2ae7c9d654f4d979feda995999fef38d791fb25706b9c884ccab3d3e9cbb017448400290b0cf2ae1d5038605cd06ad0cdb291bf12559

test:
  secret_key_base: 88fd60e46a4deea25082e925c4659462a1c85a940bfb2a007c2b2f7790cc68ecad95eb6e8fd378dd676abe2ca253cb7e074e353e2ebcf28f7d3f69d81d4ed4f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
